fuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuck

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -75,8 +75,6 @@ jobs:
   deploy:
     needs: build
     runs-on: ubuntu-latest
-    env:
-      working-directory: environments/dev/terraform
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -122,10 +120,12 @@ jobs:
           path: environments/dev/terraform/chores_lambda.zip
 
       - name: Terraform Init
+        working-directory: environments/dev/terraform
         id: init
         run: terraform init
 
       - name: Terraform Validate
+        working-directory: environments/dev/terraform
         id: validate
         run: terraform validate -no-color
 
@@ -133,8 +133,8 @@ jobs:
         working-directory: environments/dev/terraform
         id: plan
         if: github.event_name == 'pull_request'
-        run: terraform init && terraform plan -no-color
-        continue-on-error: true
+        run: terraform plan -no-color
+        # continue-on-error: true
 
 ###### source: https://github.com/hashicorp/learn-terraform-github-actions/blob/c34ebed8a1d373a992c44df2a5ba5a711df097aa/.github/workflows/terraform.yml
 #      - uses: actions/github-script@0.9.0
@@ -160,11 +160,11 @@ jobs:
 #              repo: context.repo.repo,
 #              body: output
 #            })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve
-        working-directory: environments/dev/terraform
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#
+#      - name: Terraform Apply
+#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#        run: terraform apply -auto-approve
+#        working-directory: environments/dev/terraform
